apiVersion: v2
name: drifthound
type: application
version: 0.3.2
description: A Helm chart to deploy DriftHound App on Kubernetes
appVersion: v0.3.2
home: https://github.com/treezio/drifthound
sources:
- https://github.com/treezio/drifthound
