apiVersion: v2
name: drifthound
type: application
version: 0.2.2
description: A Helm chart to deploy DriftHound App on Kubernetes
appVersion: v0.2.7
home: https://github.com/treezio/drifthound
sources:
- https://github.com/treezio/drifthound
