{{- if .Values.drifthoundSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "drifthound.fullname" . }}
  labels:
    {{- include "drifthound.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.drifthoundSecrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}