{{- if .Values.serviceAccount.enabled }}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "drifthound.fullname" . }}
  labels:
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}